/**
 * 相关函数(ctrl点击以跳转)：
 * @see metalMaterial
 * @see craftableMaterial
 * @see metalMaterialExistingMolten
 * @see customMaterial
 */
ServerEvents.recipes(event=>{
    setRecipeEvent(event)
    //重组彩钢
    metalMaterial(["tlt_tech:restructure_chromatic_steel","kubejs:molten_restructure_chromatic_steel","kubejs:restructure_chromatic_steel",7650])
    //觉醒彩钢
    metalMaterial(["tlt_tech:awaken_chromatic_steel","kubejs:molten_awaken_chromatic_steel","kubejs:awaken_chromatic_steel",16384])
    //高压彩钢
    craftableMaterial(["tlt_tech:compressed_chromatic_steel","kubejs:compressed_chromatic_steel"])
    //气锻复合钛
    craftableMaterial(["tlt_tech:pneumatic_reinforced_titanium","kubejs:pneumatic_reinforced_titanium"])
    //神匠
    metalMaterial(["kubejs:hephaestus","kubejs:molten_hephaestus","kubejs:hephaestus_ingot",7995])
    //凝矿镧
    craftableMaterial(["kubejs:orechidysprosium","kubejs:orechidysprosium"])
    //坚固板
    craftableMaterial(["kubejs:reinforced_plate","create:sturdy_sheet"])
    //红石琥珀金
    craftableMaterial(["kubejs:fluxed_electrum","redstone_arsenal:flux_plating"])
    //精灵钢
    craftableMaterial(["kubejs:alfsteel","mythicbotany:alfsteel_ingot"])
    //热力三锭
    metalMaterialExistingMolten(["kubejs:signalum","tconstruct:molten_signalum","thermal:signalum_ingot",999])
    metalMaterialExistingMolten(["kubejs:lumium","tconstruct:molten_lumium","thermal:lumium_ingot",1050])
    metalMaterialExistingMolten(["kubejs:enderium","tconstruct:molten_enderium","thermal:enderium_ingot",1350])
    //HOP石墨
    craftableMaterial(["kubejs:hop_graphite","immersiveengineering:ingot_hop_graphite"])
    //工程塑胶板
    craftableMaterial(["kubejs:duroplast","immersiveengineering:plate_duroplast"])
    //热核合金
    craftableMaterial(["kubejs:alloy_thermalnuclear","mekanism_extras:alloy_thermonuclear"])
    //辐光合金
    craftableMaterial(["kubejs:alloy_radiance","mekanism_extras:alloy_radiance"])
    //海洋玻璃碎片
    craftableMaterial(["tltmod:sea_glass_shards","alexscaves:sea_glass_shards"])
})
/**
 * 相关函数(ctrl点击以跳转)：
 * @see buildMaterial
 */
ServerEvents.highPriorityData(event=>{
    setDataEvent(event)

    //神匠
    buildMaterial('kubejs','hephaestus').setTier(8).build()
    .addStat(MaterialStatIds.HEAD,headStat(10000,64,16,MiningTiers.INFINITY))
    .addStat(MaterialStatIds.HANDLE,handleStat(1.5,1.5,1.5,1.5))
    .addStat(MaterialStatIds.GRIP,gripStat(1,1.5,16))
    .addStat(MaterialStatIds.LIMB,limbStat(10000,1.5,1.5,1))
    .addStat(MaterialStatIds.PLATING_BOOTS,platingStat(16,10000,1,16))
    .addStat(MaterialStatIds.PLATING_LEGGINS,platingStat(24,15000,1,16))
    .addStat(MaterialStatIds.PLATING_CHESTPLATE,platingStat(30,20000,1,16))
    .addStat(MaterialStatIds.PLATING_HELMET,platingStat(12,12000,1,16))
    .addStatlessStat(StatlessStatIds.BINDING).addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).build()
    .addDefault("tltmod:ever_flaming_core",1)
    .buildPerstat(MaterialTypes.MELEE).addModifier("tltmod:ever_flaming_core",1).addModifier("tltmod:stop",1).build()
    .build()

    //凝矿镧
    buildMaterial('kubejs','orechidysprosium').setTier(5).setCraftable().build()
    .addStat(MaterialStatIds.HEAD,headStat(790,6,12,MiningTiers.NETHERITE))
    .addStat(MaterialStatIds.HANDLE,handleStat(0.9,0.25,0.5,0.3))
    .addStat(MaterialStatIds.GRIP,gripStat(0.05,0.9,6))
    .addStat(MaterialStatIds.LIMB,limbStat(690,0.3,0.3,0.05))
    .addStat(MaterialStatIds.PLATING_BOOTS,platingStat(3,675,0,2))
    .addStat(MaterialStatIds.PLATING_LEGGINS,platingStat(6,795,0,2))
    .addStat(MaterialStatIds.PLATING_CHESTPLATE,platingStat(8,875,0,2))
    .addStat(MaterialStatIds.PLATING_HELMET,platingStat(4,722,0,2))
    .addStatlessStat(StatlessStatIds.BINDING).addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).build()
    .addDefault("tlt_tech:magical_ores",1).addDefault("tlt_tech:ore_capture",1).addDefault("etstlib:mana_repair",1)
    .buildPerstat(MaterialTypes.ARMOR).addModifier("tlt_tech:ore_resonance",1).addModifier("etstlib:mana_repair",2).build()
    .build()
    
    //坚固板
    buildMaterial('kubejs','reinforced_plate').setTier(4).setCraftable().build()
    .addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).build()
    .addDefault("tltmod:heat_tendency",1).addDefault("tltmod:reinforced",1)
    .build()

    //红石琥珀金
    buildMaterial('kubejs','fluxed_electrum').setTier(5).setCraftable().build()
    .addStat(MaterialStatIds.HEAD,headStat(1020,5.75,7.5,MiningTiers.NETHERITE))
    .addStat(MaterialStatIds.HANDLE,handleStat(0.2,0.25,0.2,0.25))
    .addStat(MaterialStatIds.GRIP,gripStat(0.0,0.2,5.75))
    .addStat(MaterialStatIds.LIMB,limbStat(1020,0.25,0.25,0.0))
    .addStat(MaterialStatIds.PLATING_BOOTS,platingStat(2.75,775,0.05,2))
    .addStat(MaterialStatIds.PLATING_LEGGINS,platingStat(5,809,0.05,2))
    .addStat(MaterialStatIds.PLATING_CHESTPLATE,platingStat(7,900,0.05,2))
    .addStat(MaterialStatIds.PLATING_HELMET,platingStat(3.75,735,0.05,2))
    .addStat(MaterialStatIds.FLUXCORE,fluxCoreStat(9.2,9.8))
    .addStatlessStat(StatlessStatIds.BINDING).addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).build()
    .buildPerstat(MaterialTypes.MELEE).addModifier("etstlib:energy_loaded",1).addModifier("tlt_tech:flux_slash",1).build()
    .buildPerstat(MaterialTypes.RANGED).addModifier("etstlib:energy_loaded",1).addModifier("tlt_tech:flux_infinity",1).build()
    .buildPerstat(MaterialTypes.ARMOR).addModifier("etstlib:energy_loaded",2).addModifier("tlt_tech:flux_blocking",1).build()
    .build()

    //活化彩钢调整
    buildMaterial('tinkers_advanced','activated_chromatic_steel').setTier(5).build()
    .addStat(MaterialStatIds.HEAD,headStat(1920,6.25,9,MiningTiers.NETHERITE))
    .addStat(MaterialStatIds.HANDLE,handleStat(0.3,0.5,0.3,0.25))
    .addStat(MaterialStatIds.FLUXCORE,fluxCoreStat(22.4,23.9))
    .addStat(MaterialStatIds.LIMB,limbStat(1920,0.25,0.5,0.1)).build()

    //精灵钢
    buildMaterial('kubejs','alfsteel').setTier(5).setCraftable().build()
    .addStat(MaterialStatIds.HEAD,headStat(670,5.75,6,MiningTiers.NETHERITE))
    .addStat(MaterialStatIds.HANDLE,handleStat(0.2,0.45,0.1,0.2))
    .addStat(MaterialStatIds.PLATING_BOOTS,platingStat(3,644,0,3))
    .addStat(MaterialStatIds.PLATING_LEGGINS,platingStat(5.5,768,0,3))
    .addStat(MaterialStatIds.PLATING_CHESTPLATE,platingStat(7.5,845,1,3))
    .addStat(MaterialStatIds.PLATING_HELMET,platingStat(3,700,0,3))
    .addStatlessStat(StatlessStatIds.BINDING).addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).build()
    .addDefault("tlt_tech:alf_bless",1).addDefault("etstlib:mana_repair",1)
    .buildPerstat(MaterialTypes.MELEE).addModifier("tltmod:alf_burst",1).addModifier("tlt_tech:alf_bless",1).addModifier("etstlib:mana_repair",1).build()
    .build()

    //热力三锭
    buildMaterial('kubejs','signalum').setTier(3).build()
    .addStat(MaterialStatIds.HEAD,headStat(755,5,7.5,MiningTiers.DIAMOND))
    .addStat(MaterialStatIds.HANDLE,handleStat(0.15,0.15,0.1,-0.2))
    .addStat(MaterialStatIds.LIMB,limbStat(755,-0.2,0.1,0.1))
    .addStat(MaterialStatIds.GRIP,gripStat(0.05,0.15,3))
    .addStat(MaterialStatIds.FLUXCORE,fluxCoreStat(5.2,3.8))
    .addStatlessStat(StatlessStatIds.BINDING).build()
    .addDefault("etstlib:short_circuit",1)
    .build()
    buildMaterial('kubejs','lumium').setTier(4).build()
    .addStat(MaterialStatIds.HEAD,headStat(470,4.5,2.5,MiningTiers.DIAMOND))
    .addStat(MaterialStatIds.HANDLE,handleStat(-0.15,-0.15,-0.1,0.3))
    .addStat(MaterialStatIds.LIMB,limbStat(470,0.3,-0.1,-0.05))
    .addStat(MaterialStatIds.GRIP,gripStat(0.05,-0.1,2.5))
    .addStat(MaterialStatIds.PLATING_BOOTS,platingStat(1.75,300,0,2))
    .addStat(MaterialStatIds.PLATING_LEGGINS,platingStat(4.75,467,0,2))
    .addStat(MaterialStatIds.PLATING_CHESTPLATE,platingStat(5.75,490,0,2))
    .addStat(MaterialStatIds.PLATING_HELMET,platingStat(1.75,368,0,2))
    .addStat(MaterialStatIds.FLUXCORE,fluxCoreStat(3.9,6.1))
    .addStatlessStat(StatlessStatIds.BINDING).addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).build()
    .addDefault("etstlib:glowing",1).addDefault("tconstruct:enhanced",1)
    .build()
    buildMaterial('kubejs','enderium').setTier(4).build()
    .addStat(MaterialStatIds.HEAD,headStat(1170,7,5,MiningTiers.DIAMOND))
    .addStat(MaterialStatIds.HANDLE,handleStat(0.25,0.25,0.25,0.25))
    .addStat(MaterialStatIds.LIMB,limbStat(1170,0.25,0.25,-0.05))
    .addStat(MaterialStatIds.GRIP,gripStat(0.25,0.25,5))
    .addStat(MaterialStatIds.PLATING_BOOTS,platingStat(5,980,0.05,5))
    .addStat(MaterialStatIds.PLATING_LEGGINS,platingStat(6,1159,0.05,5))
    .addStat(MaterialStatIds.PLATING_CHESTPLATE,platingStat(8,1270,0.05,5))
    .addStat(MaterialStatIds.PLATING_HELMET,platingStat(5,925,0.05,5))
    .addStat(MaterialStatIds.FLUXCORE,fluxCoreStat(5.5,5.5))
    .addStatlessStat(StatlessStatIds.BINDING).addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).build()
    .addDefault("tconstruct:enderference",1)
    .buildPerstat(MaterialTypes.ARMOR).addModifier("tinkerscalibration:enderference_armor",1).build()
    .build()

    //高定向热解石墨
    buildMaterial('kubejs','hop_graphite').setCraftable().setTier(5).build()
    .addStat(MaterialStatIds.HEAD,headStat(590,7.25,2.5,MiningTiers.WOOD))
    .addStat(MaterialStatIds.HANDLE,handleStat(-0.25,0.15,-0.25,0.75))
    .addStat(MaterialStatIds.FLUXCORE,fluxCoreStat(15.5,15.5))
    .addStatlessStat(StatlessStatIds.BINDING).addStatlessStat(StatlessStatIds.BOW_STRING).build()
    .addDefault("etstlib:short_circuit",1).addDefault("tconstruct:lightweight",2).addDefault("mushroom_concept:bloody_mary",1)
    .build()

    //辐光合金
    buildMaterial('kubejs','alloy_radiance').setTier(4).setCraftable().build()
    .addStat(MaterialStatIds.HEAD,headStat(995,8,9,MiningTiers.NETHERITE))
    .addStat(MaterialStatIds.HANDLE,handleStat(0.3,0.5,0.3,0.3))
    .addStat(MaterialStatIds.LIMB,limbStat(995,0.3,0.5,0.05))
    .addStat(MaterialStatIds.GRIP,gripStat(0.05,0.3,6))
    .addStat(MaterialStatIds.PLATING_BOOTS,platingStat(5,880,0.1,6))
    .addStat(MaterialStatIds.PLATING_LEGGINS,platingStat(7,1059,0.1,6))
    .addStat(MaterialStatIds.PLATING_CHESTPLATE,platingStat(9,1170,0.1,6))
    .addStat(MaterialStatIds.PLATING_HELMET,platingStat(5,825,0.1,6))
    .addStatlessStat(StatlessStatIds.BINDING).addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).build()
    .addDefault("etstlib:radiation_inflict",1)
    .buildPerstat(MaterialTypes.ARMOR).addModifier("etstlib:radiation_shielding",2).build()
    .build()

    //热核合金
    buildMaterial('kubejs','alloy_thermalnuclear').setCraftable().setTier(6).build()
    .addStat(MaterialStatIds.HEAD,headStat(2049,9.25,16384,MiningTiers.NETHERITE))
    .addStat(MaterialStatIds.HANDLE,handleStat(1,1,20.48,0))
    .addStat(MaterialStatIds.FLUXCORE,fluxCoreStat(69.5,69.5))
    .addStatlessStat(StatlessStatIds.BINDING).build()
    .addDefault("tlt_tech:molten_core",1)
    .build()

    //工程塑胶板
    buildMaterial('kubejs','duroplast').setCraftable().setTier(5).build()
    .addStat(MaterialStatIds.HEAD,headStat(590,9.25,2.5,MiningTiers.WOOD))
    .addStat(MaterialStatIds.HANDLE,handleStat(0.1,0.75,-0.1,0.75))
    .addStat(MaterialStatIds.FLUXCORE,fluxCoreStat(99.5,25.5))
    .addStatlessStat(StatlessStatIds.BINDING).addStatlessStat(StatlessStatIds.BOW_STRING).build()
    .addDefault("tconstruct:lightweight",2).addDefault("tinkers_advanced:metamorphium",1).addDefault("tlt_tech:industrial_born",1)
    .build()

    //鮟鱇鱼獠牙
    buildMaterial('kubejs','anglers_fang').setCraftable().setTier(4).build()
        .addStat(MaterialStatIds.HEAD,headStat(420,6.25,2.5,MiningTiers.IRON))
        .addStat(MaterialStatIds.HANDLE,handleStat(0.2,0.45,0.2,0.45))
        .build()
        .buildPerstat(MaterialTypes.MELEE).addModifier("tltmod:venom",1)
        .build()

    //剧毒獠牙,深入天境的深池毒素浇筑鮟鱇鱼獠牙
    buildMaterial('kubejs','toxic_fang').setCraftable().setTier(5).build()
        .addStat(MaterialStatIds.HEAD,headStat(520,8.25,3.5,MiningTiers.IRON))
        .addStat(MaterialStatIds.HANDLE,handleStat(0.15,0.6,0.1,0.3))
        .build()
        .buildPerstat(MaterialTypes.MELEE).addModifier("tltmod:toxic_outbreak",1)
        .build()
//    海洋玻璃碎片
    buildMaterial('tltmod','sea_glass_shards').setTier(7).setCraftable().build()
    .addStat(MaterialStatIds.HEAD,headStat(378,17,20,MiningTiers.NETHERITE))
    .addStat(MaterialStatIds.HANDLE,handleStat(-0.4,1.7,0.8,1.4))
    .addStat(MaterialStatIds.GRIP,gripStat(-0.4,-0.1,30))
    .addStat(MaterialStatIds.LIMB,limbStat(378,0.3,0.4,-0.1))
    .addStatlessStat(StatlessStatIds.BINDING).addStatlessStat(StatlessStatIds.SHIELD_CORE).build()
    .addDefault("tltmod:vibrio_vulnificus",1).addDefault("cloudertinker:fragile",1)
    .buildPerstat(MaterialTypes.ARMOR).addModifier("tltmod:vibrio_vulnificus",1).addModifier("cloudertinker:fragile",2).build()
    .build()
    //钕合金
    buildMaterial('kubejs','scarlet_neodymium').setCraftable().setTier(6).build()
    .addStat(MaterialStatIds.HEAD,headStat(3840,10,9,MiningTiers.NETHERITE))
    .addStat(MaterialStatIds.HANDLE,handleStat(0.5,1,1,0.5))
    .addStatlessStat(StatlessStatIds.BINDING).build()
    .addDefault("tltmod:warp_attack",1).addDefault("tltmod:magnetic_focus")
    .build()
    buildMaterial('kubejs','azure_neodymium').setCraftable().setTier(6).build()
    .addStat(MaterialStatIds.PLATING_BOOTS,platingStat(7,1880,1,12))
    .addStat(MaterialStatIds.PLATING_LEGGINS,platingStat(9,2059,1,12))
    .addStat(MaterialStatIds.PLATING_CHESTPLATE,platingStat(11,2170,1,12))
    .addStat(MaterialStatIds.PLATING_HELMET,platingStat(7,1825,1,12))
    .addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).build()
    .addDefault("tltmod:magnetic_scatter",1)
    .build()
    //外星三傻
    buildMaterial('tcintegrations','desh').setTier(6).build()
    .removeArmorStat()
    .addStat(MaterialStatIds.HEAD,headStat(995,8.5,12,MiningTiers.NETHERITE))
    .addStat(MaterialStatIds.HANDLE,handleStat(-0.1,0.3,0.25,0.25))
    .addStat(MaterialStatIds.GRIP,gripStat(-0.05,-0.1,8.5))
    .addStat(MaterialStatIds.LIMB,limbStat(995,0.3,0.7,-0.05))
    .addStatlessStat(StatlessStatIds.BINDING).build()
    .addDefault("tltmod:days_and_nights",1)
    .build()
    buildMaterial('tcintegrations','ostrum').setTier(6).build()
    .addStat(MaterialStatIds.HEAD,headStat(2995,12,5,MiningTiers.NETHERITE))
    .addStat(MaterialStatIds.HANDLE,handleStat(0.25,1,-0.15,-0.15))
    .addStat(MaterialStatIds.GRIP,gripStat(0.1,0.25,10.5))
    .addStat(MaterialStatIds.LIMB,limbStat(2995,-0.25,1.5,0.05))
    .addStat(MaterialStatIds.PLATING_BOOTS,platingStat(6.75,2880,1,9))
    .addStat(MaterialStatIds.PLATING_LEGGINS,platingStat(8.75,3059,1,9))
    .addStat(MaterialStatIds.PLATING_CHESTPLATE,platingStat(10,3170,1,9))
    .addStat(MaterialStatIds.PLATING_HELMET,platingStat(6.5,2825,1,9))
    .addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).addStatlessStat(StatlessStatIds.BINDING).build()
    .addDefault("tltmod:gravity_interrupt",1)
    .buildPerstat(MaterialTypes.ARMOR).addModifier("tlt_tech:flying",1).addModifier("tltmod:gravity_manipulate",1).build()
    .build()
     buildMaterial('tcintegrations','calorite').setTier(6).build()
        .removeArmorStat()
        .addStat(MaterialStatIds.HEAD,headStat(3995,20,20,MiningTiers.NETHERITE))
        .addStat(MaterialStatIds.HANDLE,handleStat(0.3,0.3,0.25,0.25))
        .addStat(MaterialStatIds.PLATING_BOOTS,platingStat(9,2980,1,9))
        .addStat(MaterialStatIds.PLATING_LEGGINS,platingStat(10.75,3259,1,9))
        .addStat(MaterialStatIds.PLATING_CHESTPLATE,platingStat(14,3370,1,9))
        .addStat(MaterialStatIds.PLATING_HELMET,platingStat(8,2925,1,9))
         addStatlessStat(StatlessStatIds.MAILLE).addStatlessStat(StatlessStatIds.SHIELD_CORE).addStatlessStat(StatlessStatIds.BINDING).build()
        .addDefault("tltmod:heat_bulge",1).addDefault("tltmod:thunder_fire")
        .buildPerstat(MaterialTypes.ARMOR).addModifier("tltmod:heat_bulge",1).addModifier("tltmod:environmental_protection",1).build()
        .build()
})
