ServerEvents.recipes(event=>{
    
    //磁极倒转
    buildModifierRecipe("tlt_tech:reverse_polarity",event)
    .addTool("tinkers_advanced:ionized_cannon")
    .addSlot(SlotTypes.ABILITIES,1)
    .addInput("mekanism:electrolytic_core",1)
    .addInput("immersiveengineering:circuit_board",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //暗蚀
    buildModifierRecipe("tltmod:dark_erosion",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.ABILITIES,1)
    .addInput("extrabotany:shadowium_ingot",1)
    .addInput("extrabotany:shadowium_ingot",1)
    .addInput("botania:mana_powder",1)
    .addInput("botania:terrasteel_ingot",1)
    .addInput("botania:mana_powder",1)
    .setAllowCrystal().setLevelRange(0,3)
    .buildRecipe().buildSalvage()

    //光刻
    buildModifierRecipe("tltmod:light_engrave",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.UPGRADES,1)
    .addInput("extrabotany:photonium_ingot",1)
    .addInput("extrabotany:photonium_ingot",1)
    .addInput("botania:mana_powder",1)
    .addInput("mythicbotany:alfsteel_ingot",1)
    .addInput("botania:mana_powder",1)
    .setAllowCrystal().setLevelRange(0,3)
    .buildRecipe().buildSalvage()

    //质荷加速
    buildModifierRecipe("tltmod:particle_accelerate",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("alexscaves:block_of_scarlet_neodymium",1)
    .addInput("extrabotany:orichalcos_ingot",1)
    .addInput("alexscaves:block_of_azure_neodymium",1)
    .addInput("alexscaves:telecore",1)
    .addInput("alexscaves:notor_gizmo",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //雷暴雨
    buildModifierRecipe("tltmod:thunderstorm",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("thermal:lightning_charge",1)
    .addInput("iceandfire:dragonsteel_lightning_ingot",1)
    .addInput("botania:thunder_sword",1)
    .addInput("ars_nouveau:glyph_lightning",1)
    .addInput("goety:lightning_focus",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //王者圣剑
    buildModifierRecipe("tltmod:excalibur_burst",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("extrabotany:excalibur",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //源混淆
    buildModifierRecipe("tltmod:source_obfuscate",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("pneumaticcraft:programming_puzzle",16)
    .addInput("pneumaticcraft:nuke_virus",1)
    .addInput("pneumaticcraft:printed_circuit_board",2)
    .addInput("botania:terrasteel_ingot",1)
    .addInput("mythicbotany:asgard_rune",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //目光远大
    buildModifierRecipe("tltmod:far_sights",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("botania:prism",1)
    .addInput("botania:gaia_ingot",1)
    .addInput("mythicbotany:fimbultyr_tablet",1)
    .addInput("botania:gaia_ingot",1)
    .addInput("botania:prism",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //射线穿刺
    buildModifierRecipe("tltmod:burst_pierce",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("botania:terrasteel_ingot",1)
    .addInput("pointed_dripstone",15)
    .addInput("pointed_dripstone",15)
    .addInput("pointed_dripstone",15)
    .addInput("botania:rune_wrath",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //破坏魔法
    buildModifierRecipe("tltmod:destruction_magic",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("botania:terra_axe",1)
    .addInput("botania:lens_mine",1)
    .addInput("botania:terra_pick",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //不稳定内存
    buildModifierRecipe("tltmod:elastic_memory",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("pneumaticcraft:programming_puzzle",16)
    .addInput("pneumaticcraft:stop_worm",1)
    .addInput("pneumaticcraft:memory_stick",1)
    .addInput("botania:labellia",4)
    .addInput("tinkers_advanced:activated_chromatic_steel",1)
    .setAllowCrystal().setLevelRange(0,3)
    .buildRecipe().buildSalvage()

    //额外战斗部
    buildModifierRecipe("tltmod:extra_warhead",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("botania:rune_mana",1)
    .addInput("botania:lens_damage",1)
    .setAllowCrystal().setLevelRange(0,5)
    .buildRecipe().buildSalvage()

    //射线扩容
    buildModifierRecipe("tltmod:more_capacity",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("botania:rune_mana",1)
    .addInput("botania:lens_power",1)
    .setAllowCrystal().setLevelRange(0,5)
    .buildRecipe().buildSalvage()

    //射线超容
    buildModifierRecipe("tltmod:over_capacity",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("botania:rune_greed",1)
    .addInput("botania:lens_power",1)
    .setAllowCrystal().setLevelRange(0,5)
    .buildRecipe().buildSalvage()

    //射线超频
    buildModifierRecipe("tltmod:overclock",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("botania:rune_fire",1)
    .addInput("botania:lens_power",1)
    .setAllowCrystal().setLevelRange(0,5)
    .buildRecipe().buildSalvage()

    //脉冲驱动器
    buildModifierRecipe("tltmod:pulse_engine",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("mekanism:teleportation_core",1)
    .addInput("mekanism:teleportation_core",1)
    .addInput("botania:lens_speed",1)
    .addInput("mekanism:teleportation_core",1)
    .addInput("mekanism:teleportation_core",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //射线加速
    buildModifierRecipe("tltmod:burst_accelerate",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("botania:mana_spreader",1)
    .addInput("botania:lens_speed",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //动能原理
    buildModifierRecipe("tltmod:burst_mass_effect",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("botania:gaia_ingot",1)
    .addInput("ad_astra:desh_plate",16)
    .addInput("ad_astra:ostrum_plate",16)
    .addInput("ad_astra:calorite_plate",16)
    .addInput("botania:gaia_ingot",1)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

    //射线破击
    buildModifierRecipe("tltmod:burst_bypass_cooldown",event)
    .addToolTag("tconstruct:modifiable/melee/primary")
    .addSlot(SlotTypes.MANA,1)
    .addInput("botania:gaia_ingot",1)
    .addInput("immersiveengineering:ingot_hop_graphite",4)
    .addInput("tinkers_advanced:basalz_signalum",4)
    .setAllowCrystal().setLevelRange(0,1)
    .buildRecipe().buildSalvage()

})
//   Item.of('tinkers_advanced:basalz_signalum')