ServerEvents.recipes(event=>{
    event.recipes.thermal.smelter(Item.of('refinedstorage:basic_processor').withChance(4),['4x minecraft:iron_ingot','4x minecraft:redstone','4x refinedstorage:silicon'])
    event.recipes.thermal.smelter(Item.of('refinedstorage:improved_processor').withChance(4),['4x minecraft:gold_ingot','4x minecraft:redstone','4x refinedstorage:silicon'])
    event.recipes.thermal.smelter(Item.of('refinedstorage:advanced_processor').withChance(4),['4x minecraft:diamond','4x minecraft:redstone','4x refinedstorage:silicon'])

    event.recipes.tconstruct.casting_basin('refinedstorage:quartz_enriched_iron_block')
        .fluid(Fluid.of('tconstruct:molten_quartz',200))
        .cast('minecraft:iron_ingot')
        .cast_consumed(true).cooling_time(100)
    
    event.recipes.tconstruct.casting_table('refinedstorage:1k_storage_part')
        .fluid(Fluid.of('tconstruct:molten_iron',90))
        .cast('refinedstorage:basic_processor')
        .cast_consumed(true).cooling_time(200)
    event.recipes.tconstruct.casting_table('refinedstorage:4k_storage_part')
        .fluid(Fluid.of('tconstruct:molten_gold',180))
        .cast('refinedstorage:improved_processor')
        .cast_consumed(true).cooling_time(200)
    event.recipes.tconstruct.casting_table('refinedstorage:16k_storage_part')
        .fluid(Fluid.of('tconstruct:molten_diamond',300))
        .cast('refinedstorage:advanced_processor')
        .cast_consumed(true).cooling_time(200)
    event.recipes.tconstruct.casting_table('refinedstorage:64k_storage_part')
        .fluid(Fluid.of('tconstruct:molten_manyullyn',360))
        .cast('refinedstorage:advanced_processor')
        .cast_consumed(true).cooling_time(200)

    event.recipes.tconstruct.casting_table('refinedstorage:64k_fluid_storage_part')
        .fluid(Fluid.of('tconstruct:molten_bronze',90))
        .cast('refinedstorage:basic_processor')
        .cast_consumed(true).cooling_time(200)
    event.recipes.tconstruct.casting_table('refinedstorage:256k_fluid_storage_part')
        .fluid(Fluid.of('tconstruct:molten_rose_gold',180))
        .cast('refinedstorage:improved_processor')
        .cast_consumed(true).cooling_time(200)
    event.recipes.tconstruct.casting_table('refinedstorage:1024k_fluid_storage_part')
        .fluid(Fluid.of('tconstruct:molten_emerald',300))
        .cast('refinedstorage:advanced_processor')
        .cast_consumed(true).cooling_time(200)
    event.recipes.tconstruct.casting_table('refinedstorage:4096k_fluid_storage_part')
        .fluid(Fluid.of('tconstruct:molten_hepatizon',360))
        .cast('refinedstorage:advanced_processor')
        .cast_consumed(true).cooling_time(200)
})